# Generated by Django 4.2.6 on 2023-11-10 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.constants


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal_type', models.CharField(choices=[('D', users.constants.GoalTypes['DAILY']), ('M', users.constants.GoalTypes['MONTHLY']), ('Y', users.constants.GoalTypes['YEARLY'])], max_length=100)),
                ('goal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commercial', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'commercials',
            },
        ),
    ]
