# Generated by Django 4.2.6 on 2023-11-10 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_commercial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercial',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commercials', to=settings.AUTH_USER_MODEL),
        ),
    ]
