# Generated by Django 4.2.6 on 2023-12-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_commercial_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('DIRECTOR', 'director'), ('ADVISER', 'asesor'), ('ASSISTANT', 'asistente')], default='asesor', max_length=100),
            preserve_default=False,
        ),
    ]
