# Generated by Django 4.2.6 on 2024-01-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercial',
            name='goal',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
