# Generated by Django 4.2.6 on 2024-01-23 04:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('brm', '0004_delete_percentage_rule_is_active_rule_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('formula', models.TextField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Percentages',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('rule', models.TextField()),
                ('director', models.DecimalField(decimal_places=2, max_digits=5)),
                ('manager', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commercial', models.DecimalField(decimal_places=2, max_digits=5)),
                ('assistant', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
