# Generated by Django 4.2.6 on 2024-01-23 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0005_remove_commission_rule_commission_percentage_and_more'),
        ('brm', '0005_formula_percentages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rule',
        ),
        migrations.AddField(
            model_name='formula',
            name='rule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='percentage', to='brm.percentages'),
        ),
    ]
