# Generated by Django 4.2.6 on 2024-01-23 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brm', '0006_delete_rule_formula_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='rule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='formula', to='brm.percentages'),
        ),
    ]
