# Generated by Django 4.2.6 on 2024-01-25 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brm', '0007_alter_formula_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='rule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='formula', to='brm.percentages'),
        ),
    ]
