# Generated by Django 4.2.6 on 2023-12-11 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brm', '0002_rule_formula'),
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='rule',
            field=models.ForeignKey(default='0b120fa4-9829-11ee-b9d1-0242ac120002', on_delete=django.db.models.deletion.DO_NOTHING, to='brm.rule'),
            preserve_default=False,
        ),
    ]
