# Generated by Django 4.2.6 on 2023-11-11 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 11, 0, 8, 45, 117197, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
