# Generated by Django 4.2.6 on 2023-11-30 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='commercial',
            new_name='user',
        ),
    ]
