# Generated by Django 4.2.6 on 2023-11-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_rename_commercial_sale_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='commissioned',
            field=models.BooleanField(default=False),
        ),
    ]
