# Generated by Django 4.2.6 on 2023-12-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_commissioned'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='commission_type',
            field=models.CharField(choices=[('SALE', 'venta'), ('DELIVERY', 'entrega'), ('OTHER', 'otros')], default='venta', max_length=100),
        ),
        migrations.AddField(
            model_name='sale',
            name='type',
            field=models.CharField(choices=[('SELF', 'propia'), ('REFERRED', 'referido'), ('DELIVER', 'entrega'), ('OTHER', 'otros')], default='propia', max_length=100),
        ),
    ]
